//Counter
export const SET_INCREMENT = 'COUNTER/SET_INCREMENT';
export const SET_DECREMENT = 'COUNTER/SET_DECREMENT';

//Todos
export const ADD_TODO = 'TODOS/ADD_TODO';
export const DELETE_TODO = 'TODOS/DELETE_TODO';
export const FETCH_TODO_START = 'TODOS/FETCH_TODO_START';
export const FETCH_TODO_SUCCESS = 'TODOS/FETCH_TODO_SUCCESS';
export const FETCH_TODO_FAILURE = 'TODOS/FETCH_TODO_FAILURE';

